-- -------------------------------------------------------------------
-- @2020, Odysseus Data Services, Inc. All rights reserved
-- MIMIC IV CDM Conversion
-- -------------------------------------------------------------------

-- -------------------------------------------------------------------
-- Populate lookups for cdm_measurement table
-- Rule 10 waveforms
-- Dependencies: run after 
--      st_waveform.sql
-- -------------------------------------------------------------------

-- -------------------------------------------------------------------
-- A draft to apply Wave Forms

-- (Manlik) Regardless of what format we end up with - is to take the meta data and map them into:

-- Procedure
-- [SNOMED.4141651] Continuous ECG monitoring
-- date/time is offset from start of monitor (1/1/1990 if no actual time is given)
-- procedure_source_value = "<wfdb reference ID - ex 3700002_0011>"

-- Device_exposure
-- [SNOMED.45758393] Patient monitoring system module, electrocardiographic
-- device_exposure_start_datetime is the date/time is offset from start of monitor (1/1/1990 if no actual time is given)
-- device_exposure_end_datetime is the start + total duration of the monitor data
-- device_source_value = "<wfdb reference ID - ex 3700002_0011>" 

-- Measurement - heart rate (1 to N), original WFDB reported or generated by our ETL
-- [SNOMED.4239408] Heart rate - units [SNOMED.4118124] bpm
-- date/time is offset from start of monitor (1/1/1990 if no actual time is given)
-- measurement_source_value = "<wfdb reference ID>.<algorithm ID> - ex "3700002_0011.WFDB" or "3700002_0011.CCSIMxv1"

-- Measurement - P-QRS-T derived measurements - aVF R-wave example
-- [LOINC.3022916] R wave amplitude in lead AVF
-- date/time is offset from start of monitor (1/1/1990 if no actual time is given) + segment offset
-- measurement_source_value = "<wfdb reference ID>.<algorithm ID> - ex 3700002_0011.CCSIMxv1"

-- I have ECG measurement map down to lead level

-- The same approach would apply to BP and Respiratory values. 

-- If we derive observations like AFib and Tachycardia - we can further map these 
-- to the condition_occurrence table as [4064452] ECG: atrial fibrillation using the same reference time and source
--
-- -------------------------------------------------------------------

-- -------------------------------------------------------------------
-- Adding a sample of Waveforms to OMOP
-- - visit_detail is the core point "to link them all"
-- - visit_detail refers to storage location
-- - visit_detail stores time of start and end of the measurement
-- - identify the visit: CAST(waveform_source.hadm_id AS STRING) = vis.visit_source_value
-- -------------------------------------------------------------------

-- from meas.chart.4: note gcpt_chart_label_to_concept

-- -------------------------------------------------------------------
-- lk_meas_waveform_mapped
-- Rule 10 (waveform)
-- reference_id = visit_detail_source_value
-- -------------------------------------------------------------------


CREATE OR REPLACE TABLE `@etl_project`.@etl_dataset.lk_meas_waveform_mapped AS
SELECT
    FARM_FINGERPRINT(GENERATE_UUID())       AS measurement_id,
    wh.subject_id                           AS subject_id,
    wh.hadm_id                              AS hadm_id,
    wm.reference_id                         AS reference_id,
    COALESCE(vc2.concept_id, 0)             AS target_concept_id,
    COALESCE(vc2.domain_id, 'Measurement')  AS target_domain_id,
    wm.mx_datetime                          AS start_datetime,
    wm.value_as_number                      AS value_as_number,
    IF(wm.unit_source_value IS NOT NULL, 
        COALESCE(uc.target_concept_id, 0), NULL)    AS unit_concept_id,
    wm.source_code                          AS source_code, 
    COALESCE(vc1.concept_id, 0)             AS source_concept_id,
    wm.unit_source_value                    AS unit_source_value,
    -- 
    'waveform_mx'                           AS unit_id,
    wm.load_table_id                        AS load_table_id,
    wm.load_row_id                          AS load_row_id,
    wm.trace_id                             AS trace_id
FROM
    `@etl_project`.@etl_dataset.src_waveform_mx wm
INNER JOIN
    `@etl_project`.@etl_dataset.src_waveform_header wh
        ON wh.reference_id = wm.reference_id
-- mapping of the main source code
-- mapping for measurement unit
LEFT JOIN
    `@etl_project`.@etl_dataset.lk_meas_unit_concept uc
        ON uc.source_code = wm.unit_source_value
        -- supposing that the standard mapping is supplemented with custom concepts for waveform specific units
LEFT JOIN
    `@etl_project`.@etl_dataset.voc_concept vc1
        ON vc1.concept_code = wm.source_code
        AND vc1.vocabulary_id = 'mimiciv_meas_waveform_code'
            -- supposing that the standard mapping is supplemented with custom concepts for waveform specific values
LEFT JOIN
    `@etl_project`.@etl_dataset.voc_concept_relationship vr
        ON vc1.concept_id = vr.concept_id_1
        AND vr.relationship_id = 'Maps to'
LEFT JOIN
    `@etl_project`.@etl_dataset.voc_concept vc2
        ON vc2.concept_id = vr.concept_id_2
        AND vc2.standard_concept = 'S'
        AND vc2.invalid_reason IS NULL
;
